### ISSUE TITLE
Set up more than one server

### ISSUE THREAD

**Issue by nicolasgnr** [jadler-mocking/jadler#119]
Hi! It it posible to set up more than one server? For example, create the first one running on port 8080 and the other on 8081, so then create routing rules individually?

**Comment by jandudek** [comment]
Hi @nicolasgnr, I'm sorry for a late response. Yes, there is a way to setup more than one mock server, each of them listening on different ports. Please take a look at the Jadler documentation (embedded in the Jadler class, http://jadler-mocking.github.io/jadler/), section "Jadler Lifecycle", header "Creating mocker instances manually".
