### ISSUE TITLE
Override all jetty dependencies to prevent conflicts with Spring

### ISSUE THREAD

**Issue by standevgd** [jadler-mocking/jadler#121]
Right now if I want to use both io.spring.platform:platform-bom and Jadler, I also need to override the following dependencies to use Jetty 8: jetty-annotations, jetty-continuation, jetty-deploy, jetty-http, jetty-io, jetty-jsp, jetty-jmx, jetty-plus, jetty-security, jetty-server, jetty-servlet, jetty-servlets, jetty-util, jetty-webapp, jetty-xml.

If all of these were in Jadler's pom, this would make the use of Jadler much easier. Created PR which adds these dependencies.

**Comment by jandudek** [comment]
Hi @standevgd, thank you for the pull request. Before I merge it I would like to understand better why you find this useful. So basically if these dependencies were directly in Jadler's pom what would be much easier for you?

**Comment by standevgd** [comment]
Hi @jandudek , if these dependencies were in Jadler's pom, I wouldn't have to override all of these jetty dependencies. My project would simply use Spring's BOM and Jadler, without having to worry about all this jetty stuff. Thank you.

@jakub-plichta FYI.

**Comment by jandudek** [comment]
I still don't get it, but let's work it out. Where exactly is the difference between having these dependencies in the Jadler pom directly VS having them transitively there from the Jetty dependency in Jadler.

@Benky could you help me here?

**Comment by standevgd** [comment]
After consulting with @jakub-plichta it seems that my changes will not solve the problem (I therefore closed PR #121). The real solution would be either to upgrade Jadler to use Jetty9, or if this is not feasible due to backward compatibility, perhaps create a separate Jadler module which would support Jetty9. So in my project I would use that new Jadler-Jetty9 module and wouldn't have to add those multiple Jetty8 dependencies anymore.

@Benky please advise if this is the right direction.

**Comment by jimirocks** [comment]
Hi @jandudek I tried to migrate jadler to jetty9 - see #123, please consider to do this upgrade - the change is easy, only two tests are questionable (since I spent on it like 10mins it's surely solvable problem)

**Comment by jimirocks** [comment]
@standevgd in the meantime, you can consider to import some bom like this: https://github.com/anthavio/anthavio-maven-poms/blob/master/jetty8-bom.pom

**Comment by jandudek** [comment]
@standevgd you can even use Jadler without any Jetty dependency. Check this article, maybe you will find it helpful: https://github.com/jadler-mocking/jadler/wiki/Using-the-Alternative-Stub-Server-Implementation
