### ISSUE TITLE
Remove Log4j from JadlerMockerTest

### ISSUE THREAD

**Issue by vorburger** [jadler-mocking/jadler#210]
Jadler currently has a dependency to Log4j. (The ancient unmaintained v1, not the v2 where the recent security issues happened.)

It's just a scope test dependency, but that still means it comes along for anyone rebuilding Jadler e.g. inside a company.

As it's only used in [JadlerMockerTest](https://github.com/jadler-mocking/jadler/blob/master/jadler-core/src/test/java/net/jadler/), which perhaps doesn't actually really need logging, I was wondering if you would perhaps be open to simply getting rid of it?

**Comment by vorburger** [comment]
If I understand correctly what `JadlerMockerTest` does with Log4j, it's that it uses Log4j to capture a Log written by [JadlerMocker](https://github.com/jadler-mocking/jadler/blob/e67b47be5c0290120969d9a301e824a15dc8493a/jadler-core/src/main/java/net/jadler/JadlerMocker.java) with the SLF4j Logging API. An alternative to do that without using Log4j could be e.g. to use the SLF4j to `java.util.logging` (JUL) bridge (AKA [`slf4j-jdk14`](https://mvnrepository.com/artifact/org.slf4j/slf4j-jdk14)) and then use e.g. https://github.com/google/guava/blob/master/guava-testlib/src/com/google/common/testing/TestLogHandler.java from https://github.com/google/guava/tree/master/guava-testlib.

Would you welcome and merge a PR for this?

**Comment by liry** [comment]
Hi Michael, thanks for reporting. I'll try to analyse it today or tomorrow and let you know.

**Comment by liry** [comment]
So, here's the PR: #212
The simplest way how to migrate from obsolete and [vulnerable](https://logging.apache.org/log4j/1.2/) log4j 1.x seemed to me to migrate to Logback, which is it's direct successor ([picking up where log4j 1.x leaves off](https://logback.qos.ch/)).
