### ISSUE TITLE
Introduce a jUnit test runner

### ISSUE THREAD

**Issue by jandudek-gdc** [jadler-mocking/jadler#28]
As discussed in https://github.com/jadler-mocking/jadler/pull/26, we should include a Jadler test runner for jUnit. It should work somehow like this:

```java
@TestRunner(JadlerTestRunner.class)
@JadlerConf(
  @DefaultStatus(201),
  @DefaultEncoding("UTF-8"),
  @DefaultContentType("text/plain"),
  [@DefaultHeader("name1", "value1"), @DefaultHeader("name2", "value2")],
  ...
)
public class MyTest {

    @Test() {
        ...
    }
}
```

The syntax is just a proposal, it will definitely change.

**Comment by jandudek** [comment]
The already existing `JadlerRule` provides the same, there is no real need for a test runner I believe.
