### ISSUE TITLE
Verification should somehow let user know why it failed

### ISSUE THREAD

**Issue by lukas-krecan-gdc** [jadler-mocking/jadler#58]
Imagine I have the following verification

    verifyThatRequest().havingBody(contains("Bla")).receivedOnce();

When it fails due to different body content, there is no way how to find out what went wrong apart from debugging. It would be nice to give some hint.

I know that it's not easy but I am sure you will figure something out.

**Comment by Kreinoee** [comment]
A simple solution could just be to print all the request received, when a verification fails. Adding the following to test with failed expectations, is typically enough for me to save me a debug session:
```
onRequest()
          .respondUsing(new Responder {
            override def nextResponse(request: Request): StubResponse = {
              println("--Got Request: " + request)
              StubResponse.builder().status(200).build()
            }
          })
```

**Comment by lukas-krecan-gdc** [comment]
You can try Hmacrest Logger https://github.com/lukas-krecan/hamcrest-logger which logs values passing through Hamcrest matchers

**Comment by jandudek** [comment]
Ok, so if a verification fails Jadler just logs all requests arrived so far. Is this a solution that would work for you?

**Comment by Kreinoee** [comment]
It would work for me, and it would be very easy so implement, compared to a solution where, Jadler should try to find the request that properly was the one that should have been passing the verifycation, and then try to diff that request to the expected.

**Comment by jandudek** [comment]
working on this

**Comment by jandudek** [comment]
So, I have a working version (need to polish it and add more tests) in https://github.com/jandudek/jadler/tree/verification-failure-reason , could you please try it locally and tell me your opinion about it?

Basically after an unsuccessful verification it prints out all requests in a form of matching and clashing predicates like this:

`
[main] [INFO] JadlerMocker.java(375) net.jadler.JadlerMocker: Verification failed, here is a list of requests received so far:
Request #1:
  matching predicates: <none>
  clashing predicates:
    REQUIRED: method is equalToIgnoringCase("DELETE") BUT was GET
    REQUIRED: body is "aaa" BUT was ""
Request #2:
  matching predicates:
    method is equalToIgnoringCase("DELETE")
  clashing predicates:
    REQUIRED: body is "aaa" BUT was ""
`

What do you think?

**Comment by Kreinoee** [comment]
Have tried your branch, and it has been working perfectly in the tests where I have tried it. Its really a giant improvement, that its now possibly to get a hint of what your are doing wrong. 

One tiny thing that could improve it a bit, would be to also print parameters that was there, but did not match any predicate. 

I have this output from a failing test:
```
matching predicates:
    method is equalToIgnoringCase("POST")
    parameter "to" is a collection containing "%2B45+22222222"
    parameter "request-id" is not null
    parameter "calling-username" is not null
  clashing predicates:
    REQUIRED: Path is "/number/+45%2011111111/start-callback" BUT was "/tnumber/+45%2011111111/start-callback"
    REQUIRED: parameter "calling-user-id" is not null BUT was null
```

The output of the path is perfect, it exactly telling me that i have written tnumber instead of number, but there is nothing directly telling met that a written calling-userid instead of calling-user-id as a parameter. This could be solved if it would print any unmatch parameters like so:

```
matching predicates:
    method is equalToIgnoringCase("POST")
    parameter "to" is a collection containing "%2B45+22222222"
    parameter "request-id" is not null
    parameter "calling-username" is not null
  clashing predicates:
    REQUIRED: Path is "/number/+45%2011111111/start-callback" BUT was "/tnumber/+45%2011111111/start-callback"
    REQUIRED: parameter "calling-user-id" is not null BUT was null
  unmatched parameters:
    calling-userid=0
```

**Comment by jandudek** [comment]
Thanks for your feedback, @ereichert! Instead of constructing the unmatched parameters/header set (which would be way too difficult given the Jadler architecture) I added a description of the whole request to the log:

```
Request #1: {method=GET, requestURI=http://localhost:36977/, parameters=[p1: value1, p2: value2], headers=[host: localhost:36977, user-agent: Jakarta Commons-HttpClient/3.1], encoding=<none>, body=<empty>}
  matching predicates: <none>
  clashing predicates:
    REQUIRED: method is equalToIgnoringCase("DELETE") BUT was GET
    REQUIRED: body is "aaa" BUT was ""
Request #2: {method=DELETE, requestURI=http://localhost:36977/, parameters=[p1: value1, p2: value2], headers=[host: localhost:36977, user-agent: Jakarta Commons-HttpClient/3.1], encoding=<none>, body=<empty>}
  matching predicates:
    method is equalToIgnoringCase("DELETE")
  clashing predicates:
    REQUIRED: body is "aaa" BUT was ""
```

I pushed it to https://github.com/jandudek/jadler/tree/verification-failure-reason again, what do you think about it?
