### ISSUE TITLE
Solve bug whne test has timout

### ISSUE THREAD

**Issue by rosell** [jadler-mocking/jadler#83]
HI!

When I try to use the @Test(timeout=100000) the  next exception is throw:

java.lang.IllegalStateException: Jadler has not been initialized yet.
	at net.jadler.Jadler.checkInitialized(Jadler.java:609)
	at net.jadler.Jadler.port(Jadler.java:582)

But If I remove the timeout attribute it works.

**Comment by jandudek** [comment]
@rosell checking this right now

**Comment by jandudek** [comment]
@rosell fix is ready and will be deployed as a part of 1.1.2. Regards, Jan

**Comment by jandudek** [comment]
@rosell 1.1.2 has been released including this fix. Jan
