### ISSUE TITLE
Jetty 9 compatilibity

### ISSUE THREAD

**Issue by chrislovecnm** [jadler-mocking/jadler#85]
Hi

Great project, just started using it internally.  Possible to get compatibility with jetty 9?

**Comment by jandudek** [comment]
Hi @chrislovecnm, thank you for using Jadler! I plan on either upgrading to jetty9 or even using some lightweight non-servlet http server. I'm working on some minor fixes for 1.1.2, then I will start working on 1.2.0, which should include this http server change.

**Comment by jandudek** [comment]
Hi @chrislovecnm, 1.2.0 is out (https://github.com/jadler-mocking/jadler/wiki/What's-new-in-1.2.0) and it provides an alternative servlet-free implementation of the stub server which can be used to avoid servlet versions conflicts (https://github.com/jadler-mocking/jadler/wiki/Using-the-Alternative-Stub-Server-Implementation).

The future versions of Jadler will drop the usage of Jetty (or any other servlets based server) eventually, until then you can use the alternative stub server.
